services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
      - rag
    environment:
      - REACT_APP_DJANGO_API_URL=http://backend:8000  # Use service name for backend
      - REACT_APP_RAG_API_URL=http://rag:8042  # Use service name for RAG


  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    env_file:
      - backend/.env

  rag:
    build: ./rag
    ports:
      - '8042:8042'
    volumes:
      - ./rag:/app

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP Neo4j Browser (Web Interface)
      - "7687:7687"  # Bolt protocol for interacting with Neo4j from application
    environment:
      NEO4J_AUTH: "neo4j/password"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - backend/.env


volumes:
  db_data:
  neo4j_data:
  neo4j_logs:

