# Generated by Django 4.2.16 on 2024-10-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_token_author_alter_token_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
